CREATE TABLE APIARIST
(
ApiaristId VARCHAR(20) PRIMARY KEY,
Password CHAR(64) NOT NULL

);



CREATE TABLE HONEY_HIVE
(
HoneyHiveId VARCHAR(20) PRIMARY KEY,
Location POINT NOT NULL,
LastInspectionDate DATE NULL,
NextInspectionDate DATE NOT NULL,


SPATIAL INDEX (Location)
);


CREATE TABLE TRANSACTION
(
TransactionId BIGINT AUTO_INCREMENT PRIMARY KEY,
TransactionType VARCHAR(8) NOT NULL,
Description VARCHAR(500) NOT NULL,
TotalAmount DECIMAL(15,2) NOT NULL,
Date DATE NOT NULL,
ApiaristId VARCHAR(6) NOT NULL,

CONSTRAINT TRANSACTION_TransactionType_CHECK
CHECK(TransactionType = 'PURCHASE' OR TransactionType = 'SALES'),

CONSTRAINT TRANSACTION_TotalAmount_CHECK
CHECK (TotalAmount >= 0),

CONSTRAINT TRANSACTION_FK
FOREIGN KEY(ApiaristId)
REFERENCES
APIARIST(ApiaristId)

ON UPDATE NO ACTION
ON DELETE NO ACTION

);


CREATE TABLE HIVE_EVENT
(
EventId BIGINT AUTO_INCREMENT PRIMARY KEY,
EventType VARCHAR(30) NOT NULL,
Description VARCHAR(500) NOT NULL,
Date DATE NOT NULL,
WeatherCondition VARCHAR(500) NOT NULL,
ApiaristId VARCHAR(20) NOT NULL,
HoneyHiveId VARCHAR(20) NOT NULL,

CONSTRAINT HIVE_EVENT_FK1
FOREIGN KEY(ApiaristId)
REFERENCES APIARIST(ApiaristId)
ON UPDATE NO ACTION
ON DELETE NO ACTION,


CONSTRAINT HIVE_EVENT_FK2
FOREIGN KEY(HoneyHiveId)
REFERENCES HONEY_HIVE(HoneyHiveId)
ON UPDATE NO ACTION
ON DELETE NO ACTION
);



CREATE TABLE COMPLETED_INSPECTION
(
InspectionId BIGINT AUTO_INCREMENT PRIMARY KEY,
HoneyHiveId VARCHAR(30) NOT NULL,
ApiaristId VARCHAR(30) NOT NULL,
InspectionDueDate DATE NOT NULL,
InspectionActualDate DATE NOT NULL,
Outcome CHAR(4) NOT NULL,
Description VARCHAR(500) NOT NULL,
WeatherCondition VARCHAR(500) NOT NULL,

CONSTRAINT COMPLETED_INSPECTION_Outcome_CHECK
CHECK( Outcome = 'PASS' OR Outcome = 'FAIL'),


CONSTRAINT COMPLETED_INSPECTION_FK1
FOREIGN KEY (HoneyHiveId)
REFERENCES HONEY_HIVE(HoneyHiveId)
ON UPDATE NO ACTION
ON DELETE NO ACTION,


CONSTRAINT COMPLETED_INSPECTION_FK2
FOREIGN KEY (ApiaristId)
REFERENCES APIARIST(ApiaristId)
ON UPDATE NO ACTION
ON DELETE NO ACTION
);




CREATE TABLE HONEY_HARVEST_BATCH
(
BatchId BIGINT AUTO_INCREMENT PRIMARY KEY,
VolumeHarvested DECIMAL(12,2) NOT NULL,
Date DATE NOT NULL,
ApiaristId VARCHAR(20) NOT NULL,
HoneyHiveId VARCHAR(20) NOT NULL,


CONSTRAINT HONEY_HARVEST_BATCH_VolumeHarvested_CHECK
CHECK (VolumeHarvested >= 0),

CONSTRAINT HONEY_HARVEST_BATCH_FK1
FOREIGN KEY (ApiaristId)
REFERENCES APIARIST(ApiaristId)
ON UPDATE NO ACTION
ON DELETE NO ACTION

);



CREATE TABLE HONEY_FLOWER
(
BatchId BIGINT NOT NULL,
FlowerName VARCHAR(40) NOT NULL,

CONSTRAINT HONEY_FLOWER_PK
PRIMARY KEY(BatchId, FlowerName),

CONSTRAINT HONEY_FLOWER_FK
FOREIGN KEY(BatchId)
REFERENCES HONEY_HARVEST_BATCH(BatchId)
ON UPDATE NO ACTION
ON DELETE NO ACTION
);


